version: "3.3"
services:
  db:
    image: postgres:14.0-alpine
    restart: always
    container_name: linkedin-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: linkedin
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./pg:/var/lib/postgresql/data
    ports:
      - 5433:5432
